# Generated by Django 5.1.5 on 2025-02-07 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0005_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userteam",
            unique_together=set(),
        ),
    ]
