# Generated by Django 5.1.5 on 2025-02-10 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0006_alter_userteam_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(through="custom_auth.UserTeam", to=settings.AUTH_USER_MODEL),
        ),
    ]
