# Generated by Django 5.1.5 on 2025-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0008_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userteam",
            name="role",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
