# Generated by Django 5.1.6 on 2025-02-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0016_remove_userteam_role_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("manager", "Manager"), ("admin", "Admin")], default="user", max_length=10
            ),
        ),
    ]
