# Generated by Django 5.1.5 on 2025-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0019_alter_notification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_1h",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_24h",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
