# Generated by Django 5.1.5 on 2025-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0022_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_1h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_24h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="TaskReminder",
        ),
    ]
