# Generated by Django 5.1.5 on 2025-02-25 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0023_task_reminder_1h_sent_task_reminder_24h_sent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="reminder_1h_sent",
        ),
        migrations.RemoveField(
            model_name="task",
            name="reminder_24h_sent",
        ),
    ]
